---
- name: Create a VM
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create a VM
    vmware_guest:
      hostname: 163.172.109.138
      validate_certs: no
      cdrom:
      - type: iso
        iso_path: "[datastore1] debian-10.9.0-amd64-netinst.iso"
        controller_type: sata
        #controller_number: 3
        #unit_number: 3
      folder: /
      name: testvm_3
    #  template: TemplateLast
      guest_id: debian10_64Guest
      disk:
      - size_gb: 1
        type: thin
        datastore: datastore1
      hardware:
        memory_mb: 512
        num_cpus: 1
        scsi: paravirtual
