
---
- name: Create VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
# get date
#- set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"
# Create a VM from a template
  - name: create the VM
    vmware_guest:
      hostname: 172.180.0.3
      username: administrator@vsphere.local
      password: Azerty77!
      validate_certs: no
      esxi_hostname: 172.180.0.5
      customization:
        dns_servers:
        - 172.180.0.2
        - 8.8.8.8
      networks:
      - name: VM Network
        start_connected: yes
        ip: 172.180.0.22
        netmask: 255.255.255.0
        gateway: 172.180.0.2
        type: static
        dns_servers:
        - 172.180.0.2
        - 8.8.8.8
      datacenter: Datacenter
      folder: /
      name: vm_test
      state: poweredon
      guest_id: ubuntu64Guest
      disk:
      - size_gb: 20
        type: thin
        datastore: LUN2
      
      hardware:
        memory_mb: 1024
        num_cpus: 1
      
      hostname: 172.180.0.3
      template: UbuntuTemplate
      wait_for_ip_address: yes
# name: add to ansible hosts file
#lineinfile:
#test: /etc/ansible/hosts
#insertafter: '^\[{{ ansible_host_group }}\]'
#line: '{{ inventory_hostname }}'
